### ISSUE TITLE
Cannot get daemon status: Error

### ISSUE THREAD

**Issue by todrobbins** [andrewosh/hyperdrive-daemon#37]
I can successfully start the daemon, but cannot get a status once it's running:

```
➜  ~ hyperdrive start
** Beta Notice: **

  The daemon's been started with simple telemetry enabled. To disable, restart with --telemetry false.

  Telemetry allows us to collect statistics such as uptime and the number of active connections.
  We do not send confidential information, such as drive keys, to our telemetry server.

✔ Hyperdrive daemon listening on localhost:3101
➜  ~ hyperdrive status
Could not get the daemon status:
Error
```

node v12.13.1
hyperdrive-daemon v1.8.1

**Comment by todrobbins** [comment]
Just double checked `hyperdrive setup`:

```
➜  ~ hyperdrive setup
Configuring FUSE...
Successfully configured FUSE:

  * FUSE is already configured.
  * Successfully created the root Hyperdrive directory.
```

**Comment by todrobbins** [comment]
Restarted my machine and everything's working as expected. I'll close for now and reopen if I encounter this again.

**Comment by andrewosh** [comment]
Hmm the daemon's not giving an informative error message there eh ;) If it happens again, there are a few things you could try that'd help debugging:

1. Install PM2 globally (`npm i pm2 -g)` then do a `pm2 list` and see if the process called `hyperdrive` is running or is errored.
2. If it's errored, maybe see if there's anything interesting at the end of the log file at `~/.hyperdrive/log.json`. Stack traces should be printed there if there's a crash.

Thanks for the issue!
