### ISSUE TITLE
'invalid auth token'

### ISSUE THREAD

**Issue by okdistribute** [andrewosh/hyperdrive-daemon#50]
**Describe the bug**
```
okdistribute@ubuntu$ hyperdrive fuse-setup
Configuring FUSE...
hFUSE successfully configured:
  * Your root drive will be mounted at ~/Hyperdrive when the daemon is next started.
  * If your mountpoint ever becomes unresponsive, try running `hyperdrive force-unmount`.
okdistribute@ubuntu$ hyperdrive start
✔ Hyperdrive daemon listening on localhost:3101
okdistribute@ubuntu$ hyperdrive status
Could not get the daemon status:
Invalid auth token.
```

I then removed the `~/.hyperdrive` folder, just in case, retried, still no luck.
```
$ hyperdrive --version
hyperdrive-daemon/1.13.8 linux-x64 node-v12.14.1
```

**Comment by andrewosh** [comment]
Hmm is it possible you have an older version of the daemon running on the machine, or perhaps the daemon didn't fully stop between when you nuked `~/.hyperdrive` and retried? 

This would happen when the CLI and the daemon are reading from different configuration directories. Ever try running the daemon with a different storage directory (the `--storage` flag)? If so, you'd need to set the `HYPERDRIVE_STORAGE` env var before running the CLI. Just thinking out loud, but I'd guess some state from a previous run is lingering around.

A few things to check:
* `pm2 list hyperdrive` is emtpy
* The `HYPERDRIVE_STORAGE` env var is not set

**Comment by okdistribute** [comment]
`pm2 delete hyperdrive` did the trick. Thanks!
