### ISSUE TITLE
Error: command setup not found

### ISSUE THREAD

**Issue by da2x** [andrewosh/hyperdrive-daemon#57]
**To Reproduce**

    $ npm install -g hyperdrive-daemon
    $ hyperdrive stats
    Could not get the drive stats:
    Error: FUSE is not configured. Please run `hyperdrive setup` first.
    $ hyperdrive setup
    Error: command setup not found

**Expected Behavior**
Setup, I guess.

**OS**
macOS 10.15.4

**Node version**
v14.3.0

**Was the daemon installed from NPM or bundled with Beaker?**
Installed from NPM.

**Comment by andrewosh** [comment]
Closed as fixed in #58
