### ISSUE TITLE
Daemon stopping due to error "Feed is closed"

### ISSUE THREAD

**Issue by hugonun** [andrewosh/hyperdrive-daemon#62]
**Describe the bug**
Daemon seems to randomly stop after I re-open Beaker when it's minimized/unused.

**To Reproduce**
I'm not sure how to reproduce, seems to happen randomly.

**Expected Behavior**
To not crash.

**OS**
Windows 10 64bit

**Node version**
v12.16.1

**Was the daemon installed from NPM or bundled with Beaker?**
Bundled

**Add any other context about the problem here.**
This started happening when I updated from Beaker v1.0.0-prerelease.2 to Beaker v1.0.0-prerelease.3. Around that time, I also started using Blahbity-blog and added ~25 profiles to my address book. Note that I downloaded Beaker yesterday, it might be unrelated to the update.

Pastebin with the log file: https://pastebin.com/YsnPaNQh

Hyperdrive status:
```
The Hyperdrive daemon is running:

  API Version:             0
  Daemon Version:          1.13.13
  Client Version:          1.15.2
  Schema Version:          1.10.0
  Hyperdrive Version:      10.11.2
  Fuse Native Version:
  Hyperdrive Fuse Version:

  Holepunchable:           true
  Remote Address:          x.x.x.x:xxxxx

  Fuse Available:          false
  Fuse Configured:         false

  Uptime:                  0 Days 1 Hours 42 Minutes 16 Seconds
```

**Comment by hugonun** [comment]
Alright, I have some updates. There was an user that made Blahbity-blog not work, it either timed out or required me to refresh the page a few times. I removed him from my address book and since then, the daemon worked fine.

Unfortunately I don't remember who the user was. I remember I couldn't load that user's profile page, it was stuck on the loading loop (didn't wait for it to time out).

**Comment by pfrazee** [comment]
Hey sorry, I didnt get around to triaging this one yet.

Do you recall where the "Feed is closed" error showed up?

**Comment by hugonun** [comment]
Hey, it was in .hyperdrive/log.old.json. You can see it in the pastebin file.

**Comment by pfrazee** [comment]
Gotcha thank you very much!

**Comment by hugonun** [comment]
I am going to close this, since it stopped happening for me. 😄
